version: "3.9"

services:
  db:
    build: ./Docker/mysql
    container_name: filmstorage-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: film_storage
      MYSQL_USER: filmuser
      MYSQL_PASSWORD: filmpass
    ports:
      - "3307:3306"  # Host port : Container port
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
