FROM mysql:8.0

# Set default charset and collation
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=film_storage
ENV MYSQL_USER=filmuser
ENV MYSQL_PASSWORD=filmpass

# Optional: copy initialization SQL
#COPY migrations/ /docker-entrypoint-initdb.d/
